implement kots release linting
Will lint a yaml-dir for a kots app. When one or more "error" type messages are found, will return with an exit code of 1. I could see a furure where we allow some sort of `--fail-threshold` param so people can have it fail on warnings too, but I'll leave that for now.

```
$ go run ./cli release lint --yaml-dir ../kots-sentry/manifests
RULE                           TYPE    START LINE    MESSAGE
config-option-password-type    warn    64            Config option "external_postgres_secretname" should have type "password"
```

For a dir with this malformed yaml file and nothing else:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: sentry
  labels:
    app: sentr
    {
data:
  config.yml: |-
    ...While a lot of configuration in Sentry can be changed via the UI, for all
```

```
$ go run ./cli release lint --yaml-dir ./manifests
RULE                TYPE     START LINE    MESSAGE
msg-yaml-invalid    error    8             missed comma between flow collection entries at line 9, column 13:
      config.yml: |-
                ^
preflight-spec       warn        Missing preflight spec
config-spec          warn        Missing config spec
troubleshoot-spec    warn        Missing troubleshoot spec
application-spec     warn        Missing application spec
Error: one or more errors found
```